import { describe, expect, it } from "vitest";
import { starterMaps } from "../../data/starterMaps";
import { createPresetLocationLayout } from "./locationLayout";
import { applyGatewayPair, DEFAULT_HOUSE_POSITION, restoreGatewayVisualPair } from "./mapGatewayVisual";
const layouts = { starter_house_interior: createPresetLocationLayout(starterMaps[0]), starter_garden: createPresetLocationLayout(starterMaps[1]) };
describe("map gateway visual", () => {
  it("restores a valid alternate pair and individual invalid coordinate components", () => { const pair = restoreGatewayVisualPair({ starter_house_interior: { gatewayLocationId: "table", proxyPosition: { x: .2, y: 2 } }, starter_garden: { gatewayLocationId: "garden", proxyPosition: { x: .8, y: .7 }, entryAffordancePosition: { x: "bad", y: .3 } } }, layouts); expect(pair.starter_house_interior).toMatchObject({ gatewayLocationId: "table", proxyPosition: { x: .2, y: layouts.starter_house_interior.table.y } }); expect(pair.starter_garden.entryAffordancePosition).toEqual({ x: DEFAULT_HOUSE_POSITION.x, y: .3 }); });
  it("restores both gateway IDs when either side is invalid without discarding valid display values", () => { const pair = restoreGatewayVisualPair({ starter_house_interior: { gatewayLocationId: "", proxyPosition: { x: .2, y: .3 } }, starter_garden: { gatewayLocationId: "garden", proxyPosition: { x: .8, y: .7 }, entryAffordancePosition: { x: .4, y: .3 } } }, layouts); expect(pair.starter_house_interior.gatewayLocationId).toBe("entrance"); expect(pair.starter_garden.gatewayLocationId).toBe("front_of_house"); expect(pair.starter_garden.proxyPosition).toEqual({ x: .8, y: .7 }); });
  it("overlays one bidirectional gateway without mutating presets or adjacency", () => { const before = structuredClone(starterMaps); const pair = restoreGatewayVisualPair({ starter_house_interior: { gatewayLocationId: "table" }, starter_garden: { gatewayLocationId: "garden" } }, layouts); const maps = applyGatewayPair(starterMaps, pair); expect(maps[0].locations.find((x) => x.locationId === "table")?.gateway?.destinationLocationId).toBe("garden"); expect(maps[1].locations.find((x) => x.locationId === "garden")?.gateway?.destinationLocationId).toBe("table"); expect(maps[0].locations.find((x) => x.locationId === "entrance")?.gateway).toBeUndefined(); expect(starterMaps).toEqual(before); });
});
