export const itemCategories = ["food", "drink", "plant", "book", "tool", "craft", "photo", "gift", "furniture", "clothing", "toy", "storage", "memory", "misc"] as const;
export type ItemCategory = typeof itemCategories[number];
export type ItemSource = "preset" | "user" | "event";
export type ItemVisual = { iconKey: string; genericVisualKey: string | null; imageAssetId: string | null; mapDisplayMode: "icon" | "image" | "auto" };
export type GameItem = { itemId: string; name: string; category: ItemCategory; description: string; tags: string[]; source: ItemSource; visual: ItemVisual; createdAt: string; updatedAt: string };
export type ResolvedItemVisual = { kind: "image"; assetId: string } | { kind: "generic"; key: string } | { kind: "icon"; iconKey: string };

export const categoryLabels: Record<ItemCategory, string> = { food: "食べ物", drink: "飲み物", plant: "植物", book: "本・紙もの", tool: "道具", craft: "工作材料", photo: "写真", gift: "贈り物", furniture: "家具・装飾", clothing: "衣類・布もの", toy: "玩具", storage: "収納", memory: "思い出品", misc: "その他" };
const defaults: Record<ItemCategory, readonly [string, string]> = { food: ["restaurant", "food"], drink: ["local_cafe", "drink"], plant: ["potted_plant", "plant"], book: ["menu_book", "book"], tool: ["handyman", "tool"], craft: ["construction", "craft"], photo: ["photo", "photo"], gift: ["redeem", "gift"], furniture: ["chair", "furniture"], clothing: ["apparel", "clothing"], toy: ["toys", "toy"], storage: ["inventory_2", "storage"], memory: ["favorite", "memory"], misc: ["category", "misc"] };
export const getDefaultItemVisual = (category: ItemCategory): ItemVisual => ({ iconKey: defaults[category][0], genericVisualKey: defaults[category][1], imageAssetId: null, mapDisplayMode: "icon" });

const presetDate = "2026-01-01T00:00:00.000Z";
const starter = (itemId: string, name: string, category: ItemCategory, description: string, iconKey?: string): GameItem => ({ itemId, name, category, description, tags: [], source: "preset", visual: iconKey ? { ...getDefaultItemVisual(category), iconKey } : getDefaultItemVisual(category), createdAt: presetDate, updatedAt: presetDate });
export const starterItems: GameItem[] = [starter("starter_umbrella", "傘", "tool", "雨の日のために置いてある傘。", "umbrella"), starter("starter_mug", "マグカップ", "drink", "日々の飲み物に使うマグカップ。"), starter("starter_book", "本", "book", "静かな時間に開ける一冊の本。"), starter("starter_snack", "おやつ", "food", "二人で食べられる小さなおやつ。"), starter("starter_watering_can", "ジョウロ", "tool", "庭の植物へ水をあげるためのジョウロ。"), starter("starter_toolbox", "工具箱", "tool", "工作や手入れに使う道具をまとめた箱。")];

const control = /[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/u;
export const parseItem = (value: unknown): GameItem | null => {
  if (!value || typeof value !== "object" || Array.isArray(value)) return null;
  const v = value as Record<string, unknown>, visual = v.visual as Record<string, unknown> | null;
  if (typeof v.itemId !== "string" || v.itemId.length < 1 || v.itemId.length > 100 || control.test(v.itemId) || typeof v.name !== "string" || v.name !== v.name.trim() || v.name.length < 1 || v.name.length > 40 || control.test(v.name) || !itemCategories.includes(v.category as ItemCategory) || typeof v.description !== "string" || v.description !== v.description.trim() || v.description.length > 280 || control.test(v.description) || !Array.isArray(v.tags) || v.tags.length > 12 || !v.tags.every((tag) => typeof tag === "string" && tag === tag.trim() && tag.length >= 1 && tag.length <= 24 && !control.test(tag)) || new Set(v.tags).size !== v.tags.length || !["preset", "user", "event"].includes(v.source as string) || !visual || typeof visual.iconKey !== "string" || visual.iconKey.length < 1 || !(visual.genericVisualKey === null || typeof visual.genericVisualKey === "string") || visual.imageAssetId !== null || visual.mapDisplayMode !== "icon" || typeof v.createdAt !== "string" || !Number.isFinite(Date.parse(v.createdAt)) || typeof v.updatedAt !== "string" || !Number.isFinite(Date.parse(v.updatedAt))) return null;
  return { itemId: v.itemId, name: v.name, category: v.category as ItemCategory, description: v.description, tags: [...v.tags] as string[], source: v.source as ItemSource, visual: visual as ItemVisual, createdAt: v.createdAt, updatedAt: v.updatedAt };
};
export const mergeStarterItems = (values: unknown[]): GameItem[] => { const valid = new Map<string, GameItem>(); values.forEach((value) => { const item = parseItem(value); if (item && !valid.has(item.itemId)) valid.set(item.itemId, item); }); starterItems.forEach((item) => { if (!valid.has(item.itemId)) valid.set(item.itemId, structuredClone(item)); }); return [...valid.values()]; };
export const createUserItem = (input: { name: string; category: ItemCategory; description?: string }, id: () => string, now: () => string): GameItem => { const candidate = { itemId: id(), name: input.name.trim(), category: input.category, description: (input.description ?? "").trim(), tags: [], source: "user" as const, visual: getDefaultItemVisual(input.category), createdAt: now(), updatedAt: now() }; const parsed = parseItem(candidate); if (!parsed) throw new Error("名前は1〜40文字、説明は280文字以内で入力してください。制御文字は使えません。"); return parsed; };
export const resolveItemVisual = (item: GameItem): ResolvedItemVisual => ({ kind: "icon", iconKey: item.visual.iconKey });
