import { Store, type ItemDraft } from "./Store";
import { HomeScreen } from "../ui/screens/HomeScreen";
import type { CharacterId } from "../domain/characters/characterTypes";
import type { LocationRef } from "../domain/maps/mapTypes";
import type { SaveCoordinator } from "../persistence/saveCoordinator";
import { PartnerActivityController } from "./PartnerActivityController";
import { createPendingConsultation, extractJsonObject, validateUnknownSproutResult, type AppliedUnknownSproutExtension, type ConsultationCheckpoint } from "../domain/consultation/unknownSproutConsultation";
import { applyPartnerResult, createPartnerConsultation, restorePartnerSnapshot, validatePartnerResult } from "../domain/partner/partnerProfile";
import { createUserItem } from "../domain/items/items";
import { validateItemImage, type ItemImageAsset, type ItemImageMimeType } from "../domain/assets/itemImages";
import type { ItemImageUi } from "../ui/screens/ItemsScreen";

const MOVEMENT_STEP_MS = 380;

export class App {
  private movementTimers = new Map<CharacterId, number>();
  private partner: PartnerActivityController;
  private itemImage: ItemImageUi = { phase: "icon", url: null };
  private selectedImageFile: File | null = null;
  private imageGeneration = 0;
  constructor(private root: HTMLElement, private store = new Store(), private saves?: SaveCoordinator) { this.partner = new PartnerActivityController(store, (destination, done) => this.move("cody", destination, done)); }
  mount(): void {
    this.store.subscribe((state) => { this.render(); void this.saves?.save(state); });
    this.render();
    this.partner.start();
    this.store.checkEvents();
    document.addEventListener("visibilitychange", this.onVisibility);
  }
  private render(): void {
    const actions = {
      map: (id: Parameters<Store["setViewedMap"]>[0]) => this.store.setViewedMap(id),
      navigation: (id: Parameters<Store["setNavigation"]>[0]) => { this.clearItemImage(); this.store.setNavigation(id); },
      developer: (open?: boolean) => this.store.toggleDeveloperPanel(open),
      move: (characterId: CharacterId, destination: LocationRef) => this.move(characterId, destination),
      pausePartner: () => this.partner.pause(), resumePartner: () => this.partner.resume(), decidePartner: () => this.partner.decideNow(),
      openEvent: () => this.store.openEvent(), closeEvent: () => { this.store.closeEvent(); requestAnimationFrame(() => document.querySelector<HTMLElement>('[data-focus-key="event-unknown_sprout"]')?.focus()); }, advanceEvent: (choice: Parameters<Store["advanceEvent"]>[0]) => { this.store.advanceEvent(choice); }, triggerEvent: () => this.store.triggerEvent(), resetEvent: () => this.store.resetEvent(),
      reset: () => { this.stopTimers(); this.store.reset(); this.partner.reset(); void this.saves?.save(this.store.getState(), true); },
      startConsultation: () => void this.startConsultation(), setConsultationResponse: (value: string) => this.store.setConsultation({ consultationResponse: value, consultationMessage: "" }), checkConsultation: () => this.checkConsultation(), editConsultation: () => this.store.setConsultation({ consultationView: "compose", consultationPreview: null, consultationMessage: "返答を修正できます。" }), cancelConsultation: () => this.store.setConsultation({ consultationView: "closed", consultationPreview: null, consultationMessage: "" }), applyConsultation: () => void this.applyConsultation(), startPartnerConsultation: () => void this.startPartnerConsultation(), setPartnerResponse: (value: string) => this.store.setPartner({ partnerResponse: value, partnerMessage: "" }), checkPartnerResponse: () => this.checkPartnerResponse(), editPartnerResponse: () => this.store.setPartner({ partnerView: "consult", partnerPreview: null, partnerMessage: "返答を修正できます。" }), closePartnerFlow: () => this.store.setPartner({ partnerView: "profile", partnerPreview: null }), discardPartnerConsultation: () => void this.discardPartnerConsultation(), applyPartner: () => void this.applyPartner(), showPartnerHistory: () => this.store.setPartner({ partnerView: "history" }), showPartnerRevision: (revision: number) => this.store.setPartner({ partnerView: "history_detail", selectedPartnerRevision: revision }), confirmPartnerRestore: () => this.store.setPartner({ partnerView: "restore_confirm" }), applyPartnerRestore: () => void this.applyPartnerRestore(), showItemList: () => { const id = this.store.getState().selectedItemId; this.clearItemImage(); this.store.setItemView("list"); requestAnimationFrame(() => document.querySelector<HTMLElement>(`[data-item-id="${CSS.escape(id ?? "")}"]`)?.focus()); }, showItemDetail: (id: string) => { this.clearItemImage(); this.store.setItemView("detail", id); void this.loadItemImage(id); requestAnimationFrame(() => document.querySelector<HTMLElement>("#items-heading")?.focus()); }, showItemCreate: () => { this.clearItemImage(); this.store.setItemView("create"); requestAnimationFrame(() => document.querySelector<HTMLElement>("#items-heading")?.focus()); }, updateItemDraft: (next: Partial<ItemDraft>) => this.store.cacheItemDraft(next), createItem: () => this.createItem(this.store.getState().itemDraft), chooseItemImage: (file: File) => void this.chooseItemImage(file), saveItemImage: () => void this.saveItemImage(), cancelItemImage: () => this.cancelItemImage(), confirmDeleteItemImage: () => { this.itemImage = { ...this.itemImage, phase: "delete_confirm" }; this.render(); }, deleteItemImage: () => void this.deleteItemImage()
    };
    this.root.replaceChildren(HomeScreen(this.store.getState(), actions, this.itemImage));
  }
  private setItemImage(next: ItemImageUi): void { this.itemImage = next; this.render(); }
  private revokeItemUrl(): void { if (this.itemImage.url) URL.revokeObjectURL(this.itemImage.url); }
  private clearItemImage(): void { this.imageGeneration++; this.revokeItemUrl(); this.itemImage = { phase: "icon", url: null }; this.selectedImageFile = null; }
  private async loadItemImage(itemId: string): Promise<void> { const item = this.store.getState().items.find((value) => value.itemId === itemId); const assetId = item?.visual.imageAssetId; if (!assetId || !this.saves) return; const generation = ++this.imageGeneration; this.setItemImage({ phase: "loading", url: null }); try { const asset = await this.saves.getItemImage(assetId); if (generation !== this.imageGeneration || this.store.getState().selectedItemId !== itemId) return; if (!asset || asset.metadata.assetId !== assetId || asset.metadata.ownerId !== itemId) { this.setItemImage({ phase: "error", url: null, message: "画像を読み込めなかったため、アイコンを表示しています。" }); return; } this.setItemImage({ phase: "image", url: URL.createObjectURL(asset.blob) }); } catch { if (generation === this.imageGeneration) this.setItemImage({ phase: "error", url: null, message: "画像を読み込めなかったため、アイコンを表示しています。" }); } }
  private async chooseItemImage(file: File): Promise<void> { try { const mimeType = await validateItemImage(file); this.revokeItemUrl(); this.selectedImageFile = file; this.setItemImage({ phase: "preview", url: URL.createObjectURL(file), fileName: file.name, mimeType, byteSize: file.size }); } catch (error) { this.selectedImageFile = null; this.revokeItemUrl(); this.setItemImage({ phase: "error", url: null, message: error instanceof Error ? error.message : "画像を確認できませんでした。" }); } }
  private async saveItemImage(): Promise<void> { const item = this.store.getState().items.find((value) => value.itemId === this.store.getState().selectedItemId), file = this.selectedImageFile; if (!item || !file || !this.saves || !this.itemImage.mimeType) return; const mimeType = this.itemImage.mimeType as ItemImageMimeType, now = new Date().toISOString(), assetId = makeId(); const asset: ItemImageAsset = { metadata: { assetId, kind: "item_image", ownerId: item.itemId, mimeType, byteSize: file.size, originalName: file.name, createdAt: now, updatedAt: now }, blob: file }; this.setItemImage({ ...this.itemImage, phase: "saving" }); try { const updated = await this.saves.putItemImage(item.itemId, asset); this.store.replaceItem(updated, "画像を保存しました。"); this.selectedImageFile = null; this.revokeItemUrl(); this.itemImage = { phase: "image", url: URL.createObjectURL(file), message: "画像を保存しました。" }; this.render(); } catch { this.setItemImage({ ...this.itemImage, phase: "preview", message: "保存できませんでした。選択画像を残しています。もう一度お試しください。" }); } }
  private cancelItemImage(): void { const id = this.store.getState().selectedItemId; this.clearItemImage(); if (id) void this.loadItemImage(id); }
  private async deleteItemImage(): Promise<void> { const id = this.store.getState().selectedItemId; if (!id || !this.saves) return; try { const updated = await this.saves.deleteItemImage(id); this.clearItemImage(); this.store.replaceItem(updated, "画像だけを削除しました。アイテム本体は残っています。"); } catch { this.setItemImage({ ...this.itemImage, phase: this.itemImage.url ? "image" : "error", message: "画像を削除できませんでした。以前の画像は残っています。" }); } }
  private async startConsultation(): Promise<void> { const state = this.store.getState(); if (state.unknownSprout.status !== "completed" || state.unknownSproutExtension) return; if (state.pendingPartnerConsultation) { this.store.setConsultation({ consultationMessage: "パートナー設定の相談が保留中です。" }); return; } if (state.pendingConsultation) { this.store.setConsultation({ consultationView: "compose" }); return; } const pending = createPendingConsultation(state.unknownSprout.path, makeId(), new Date().toISOString()); try { await this.saves?.savePending(pending); this.store.setConsultation({ pendingConsultation: pending, consultationView: "compose", consultationMessage: "送信用プロンプトを用意しました。" }); } catch { this.store.setConsultation({ consultationMessage: "相談を保存できませんでした。もう一度お試しください。" }); } }
  private checkConsultation(): void { const state = this.store.getState(); if (!state.pendingConsultation) return; try { const preview = validateUnknownSproutResult(extractJsonObject(state.consultationResponse), state.pendingConsultation, state.unknownSprout, state.unknownSproutExtension); this.store.setConsultation({ consultationPreview: preview, consultationView: "confirm", consultationMessage: "内容を検証しました。まだ反映されていません。" }); } catch (error) { this.store.setConsultation({ consultationMessage: error instanceof Error ? error.message : "返答を確認できませんでした。" }); } }
  private async applyConsultation(): Promise<void> { const state = this.store.getState(); const pending = state.pendingConsultation; const result = state.consultationPreview; if (!pending || !result || state.unknownSprout.status !== "completed" || state.unknownSprout.path !== result.expectedPath || state.unknownSproutExtension) { this.store.setConsultation({ consultationMessage: "花の状態が変わったため反映できません。" }); return; } const now = new Date().toISOString(); const extension: AppliedUnknownSproutExtension = { requestId: result.requestId, flowerName: result.flowerName, partnerLine: result.partnerLine, note: result.note, appliedAt: now }; const checkpoint: ConsultationCheckpoint = { checkpointId: makeId(), requestId: result.requestId, eventId: "unknown_sprout", createdAt: now, eventBefore: structuredClone(state.unknownSprout), extensionBefore: state.unknownSproutExtension }; try { await this.saves?.apply({ ...state, unknownSproutExtension: extension }, pending, extension, checkpoint); this.store.setConsultation({ unknownSproutExtension: extension, pendingConsultation: null, consultationPreview: null, consultationResponse: "", consultationView: "closed", consultationMessage: "" }); } catch { this.store.setConsultation({ consultationMessage: "保存できなかったため反映していません。もう一度お試しください。" }); } }
  private async startPartnerConsultation(): Promise<void> { const state = this.store.getState(); if (state.pendingConsultation) { this.store.setPartner({ partnerMessage: "花の相談が保留中です。先に完了してください。" }); return; } if (state.pendingPartnerConsultation) { this.store.setPartner({ partnerView: "consult" }); return; } const pending = createPartnerConsultation(state.partnerProfile, state.partnerDialogues, makeId(), new Date().toISOString()); try { await this.saves?.savePendingPartner(pending); this.store.setPartner({ pendingPartnerConsultation: pending, partnerView: "consult", partnerMessage: "送信用プロンプトを用意しました。" }); } catch { this.store.setPartner({ partnerMessage: "相談を保存できませんでした。" }); } }
  private async discardPartnerConsultation(): Promise<void> { const pending = this.store.getState().pendingPartnerConsultation; if (!pending) { this.store.setPartner({ partnerView: "profile" }); return; } try { await this.saves?.discardPartner(pending); this.store.setPartner({ pendingPartnerConsultation: null, partnerPreview: null, partnerResponse: "", partnerView: "profile", partnerMessage: "相談を破棄しました。" }); } catch { this.store.setPartner({ partnerMessage: "相談を破棄できませんでした。" }); } }
  private checkPartnerResponse(): void { const state = this.store.getState(); if (!state.pendingPartnerConsultation) return; try { const preview = validatePartnerResult(extractJsonObject(state.partnerResponse), state.pendingPartnerConsultation, state.partnerProfile, state.partnerDialogues); this.store.setPartner({ partnerPreview: preview, partnerView: "confirm", partnerMessage: "差分を検証しました。まだ反映されていません。" }); } catch (error) { this.store.setPartner({ partnerMessage: error instanceof Error ? error.message : "返答を確認できませんでした。" }); } }
  private async applyPartner(): Promise<void> { const state = this.store.getState(), pending = state.pendingPartnerConsultation, result = state.partnerPreview; if (!pending || !result || pending.expectedRevision !== state.partnerProfile.revision) { this.store.setPartner({ partnerMessage: "設定が変わったため反映できません。" }); return; } const now = new Date().toISOString(), next = applyPartnerResult(state.partnerProfile, state.partnerDialogues, result, now, makeId); const characters = state.characters.map((character) => character.characterId === "cody" ? { ...character, name: next.profile.displayName } : character); try { await this.saves?.applyPartner({ ...state, characters }, pending, next, { checkpointId: makeId(), createdAt: now }); this.store.setPartner({ partnerProfile: next.profile, partnerDialogues: next.dialogues, partnerHistory: [...state.partnerHistory, next], characters, pendingPartnerConsultation: null, partnerPreview: null, partnerResponse: "", partnerView: "profile", partnerMessage: "設定を反映しました。次の行動から使用します。" }); } catch { this.store.setPartner({ partnerMessage: "保存できなかったため反映していません。返答を残して再試行できます。" }); } }
  private async applyPartnerRestore(): Promise<void> { const state = this.store.getState(), source = state.partnerHistory.find((item) => item.profile.revision === state.selectedPartnerRevision); if (!source || source.profile.revision === state.partnerProfile.revision) return; const now = new Date().toISOString(), next = restorePartnerSnapshot(state.partnerProfile, source, now), characters = state.characters.map((character) => character.characterId === "cody" ? { ...character, name: next.profile.displayName } : character); try { await this.saves?.applyPartner({ ...state, characters }, null, next, { checkpointId: makeId(), createdAt: now }); this.store.setPartner({ partnerProfile: next.profile, partnerDialogues: next.dialogues, partnerHistory: [...state.partnerHistory, next], characters, partnerView: "profile", partnerMessage: `revision ${source.profile.revision} を新しいrevisionとして復元しました。` }); } catch { this.store.setPartner({ partnerMessage: "保存できなかったため復元していません。" }); } }
  private async createItem(input: ItemDraft): Promise<string | null> { try { const item = createUserItem(input, makeId, () => new Date().toISOString()); const state = this.store.getState(); if (!this.saves) throw new Error("保存を利用できないため登録していません。"); await this.saves.saveItems({ ...state, items: [...state.items, item] }); this.store.addItem(item); requestAnimationFrame(() => document.querySelector<HTMLElement>("#items-heading")?.focus()); return null; } catch (error) { const message = error instanceof Error ? error.message : "保存できなかったため登録していません。もう一度お試しください。"; this.store.setItemMessage(message); return message; } }
  private move(characterId: CharacterId, destination: LocationRef, done?: (arrived: boolean) => void): void {
    const result = this.store.beginMovement(characterId, destination); if (result !== "started") { done?.(result === "same"); return; }
    if (matchMedia("(prefers-reduced-motion: reduce)").matches) { while (this.store.advanceCharacter(characterId)) { /* apply the complete route */ } done?.(true); return; }
    const step = (): void => { if (this.store.advanceCharacter(characterId)) this.movementTimers.set(characterId, window.setTimeout(step, MOVEMENT_STEP_MS)); else { this.movementTimers.delete(characterId); done?.(true); } };
    this.movementTimers.set(characterId, window.setTimeout(step, MOVEMENT_STEP_MS));
  }
  private onVisibility = (): void => { if (document.visibilityState === "visible") this.store.checkEvents(); };
  private stopTimers(): void { this.movementTimers.forEach((timer) => clearTimeout(timer)); this.movementTimers.clear(); }
}
const makeId = (): string => { if (typeof crypto.randomUUID === "function") return crypto.randomUUID(); const bytes = new Uint8Array(16); crypto.getRandomValues(bytes); return [...bytes].map((value) => value.toString(16).padStart(2, "0")).join(""); };
