import type { AppState, ItemDraft } from "../../app/Store";
import { categoryLabels, itemCategories, resolveItemVisual } from "../../domain/items/items";
import { ItemIcon } from "../icons/itemIcons";
import type { ItemImageMimeType } from "../../domain/assets/itemImages";

export type ItemImageUi = { phase: "icon" | "loading" | "image" | "preview" | "saving" | "delete_confirm" | "error"; url: string | null; fileName?: string; mimeType?: ItemImageMimeType; byteSize?: number; message?: string };
export type ItemScreenActions = { showItemList: () => void; showItemDetail: (id: string) => void; showItemCreate: () => void; updateItemDraft: (next: Partial<ItemDraft>) => void; createItem: () => Promise<string | null>; chooseItemImage: (file: File) => void; saveItemImage: () => void; cancelItemImage: () => void; confirmDeleteItemImage: () => void; deleteItemImage: () => void };
export const ItemsScreen = (state: AppState, actions: ItemScreenActions, image: ItemImageUi = { phase: "icon", url: null }): HTMLElement => state.itemView === "create" ? createScreen(state, actions) : state.itemView === "detail" ? detailScreen(state, actions, image) : listScreen(state, actions);
const base = (title: string): [HTMLElement, HTMLElement] => { const section = document.createElement("section"); section.className = "content-card items-screen"; const heading = document.createElement("h2"); heading.id = "items-heading"; heading.tabIndex = -1; heading.textContent = title; section.setAttribute("aria-labelledby", heading.id); return [section, heading]; };
const live = (message: string): HTMLElement => { const node = document.createElement("p"); node.className = "item-live"; node.setAttribute("role", "status"); node.setAttribute("aria-live", "polite"); node.textContent = message; return node; };
const listScreen = (state: AppState, actions: ItemScreenActions): HTMLElement => { const [section, heading] = base("アイテム"); const count = document.createElement("p"); count.className = "eyebrow"; count.textContent = `${state.items.length}件登録`; const create = button("アイテムを登録", actions.showItemCreate, "primary-button item-create-button"); const list = document.createElement("div"); list.className = "item-list"; const ordered = [...state.items].sort((a, b) => (a.source === "preset" ? 0 : 1) - (b.source === "preset" ? 0 : 1) || a.name.localeCompare(b.name, "ja") || a.itemId.localeCompare(b.itemId)); ordered.forEach((item) => { const row = button("", () => actions.showItemDetail(item.itemId), "item-row"); row.dataset.itemId = item.itemId; row.append(ItemIcon(item.visual.iconKey)); const copy = document.createElement("span"); const name = document.createElement("strong"); name.textContent = item.name; const category = document.createElement("small"); category.textContent = categoryLabels[item.category]; copy.append(name, category); row.append(copy); list.append(row); }); section.append(heading, count, create, list, live(state.itemMessage)); return section; };
const detailScreen = (state: AppState, actions: ItemScreenActions, image: ItemImageUi): HTMLElement => { const item = state.items.find(({ itemId }) => itemId === state.selectedItemId); if (!item) return listScreen(state, actions); const [section, heading] = base(item.name); const back = button("一覧へ戻る", actions.showItemList); const visual = resolveItemVisual(item); const hero = document.createElement("div"); hero.className = "item-hero"; hero.append(ItemIcon(visual.kind === "icon" ? visual.iconKey : "category", item.name)); if ((image.phase === "image" || image.phase === "preview" || image.phase === "saving" || image.phase === "delete_confirm") && image.url) { const img = document.createElement("img"); img.src = image.url; img.alt = `${item.name}の画像`; hero.append(img); hero.classList.add("has-image"); }
  const controls = document.createElement("div"); controls.className = "item-image-controls"; const input = document.createElement("input"); input.type = "file"; input.accept = "image/png,image/jpeg,image/webp"; input.id = "item-image-file"; input.addEventListener("change", () => { const file = input.files?.[0]; if (file) actions.chooseItemImage(file); input.value = ""; }); const inputLabel = document.createElement("label"); inputLabel.htmlFor = input.id; inputLabel.className = "button-label"; inputLabel.textContent = item.visual.imageAssetId ? "画像を変更" : "画像を追加";
  if (image.phase === "preview" || image.phase === "saving") { controls.append(text(`ファイル名：${image.fileName ?? ""}`), text(`形式：${image.mimeType ?? ""}`), text(`容量：${formatBytes(image.byteSize ?? 0)}`), button(image.phase === "saving" ? "保存中…" : "この画像を保存", actions.saveItemImage, "primary-button"), inputLabel, input, button("キャンセル", actions.cancelItemImage)); (controls.querySelector("button") as HTMLButtonElement).disabled = image.phase === "saving"; }
  else if (image.phase === "delete_confirm") controls.append(text("画像だけを削除します。アイテム本体、名前、カテゴリ、説明は残ります。"), button("画像だけを削除する", actions.deleteItemImage, "primary-button"), button("キャンセル", actions.cancelItemImage));
  else { controls.append(inputLabel, input); if (item.visual.imageAssetId) controls.append(button("画像を削除", actions.confirmDeleteItemImage)); }
  const category = document.createElement("p"); category.textContent = `カテゴリ：${categoryLabels[item.category]}`; const description = document.createElement("p"); description.className = "item-description"; description.textContent = item.description || "説明はありません。"; const source = document.createElement("p"); source.className = "eyebrow"; source.textContent = item.source === "preset" ? "プリセット" : item.source === "user" ? "ユーザー登録" : "イベント"; const status = live(image.phase === "loading" ? "画像を読み込んでいます。" : image.message ?? state.itemMessage); section.append(back, hero, heading, controls, category, description, source, status); return section; };
const createScreen = (state: AppState, actions: ItemScreenActions): HTMLElement => { const [section, heading] = base("アイテムを登録"); const form = document.createElement("form"); form.className = "item-form"; const name = inputGroup("アイテム名", "item-name", "input") as HTMLInputElement; name.maxLength = 40; name.required = true; name.value = state.itemDraft.name; name.addEventListener("input", () => actions.updateItemDraft({ name: name.value })); const category = document.createElement("select"); category.id = "item-category"; itemCategories.forEach((id) => { const option = document.createElement("option"); option.value = id; option.textContent = categoryLabels[id]; category.append(option); }); category.value = state.itemDraft.category; category.addEventListener("change", () => actions.updateItemDraft({ category: category.value as ItemDraft["category"] })); const categoryLabel = document.createElement("label"); categoryLabel.htmlFor = category.id; categoryLabel.textContent = "カテゴリ"; const description = inputGroup("説明（任意）", "item-description", "textarea") as HTMLTextAreaElement; description.maxLength = 280; description.value = state.itemDraft.description; description.addEventListener("input", () => actions.updateItemDraft({ description: description.value })); const message = live(state.itemMessage); const submit = button("登録する", () => undefined, "primary-button"); submit.type = "submit"; form.append(labelFor(name), name, categoryLabel, category, labelFor(description), description, message, submit, button("キャンセル", actions.showItemList)); form.addEventListener("submit", async (event) => { event.preventDefault(); actions.updateItemDraft({ name: name.value, category: category.value as ItemDraft["category"], description: description.value }); submit.disabled = true; const error = await actions.createItem(); if (error && message.isConnected) { message.textContent = error; submit.disabled = false; } }); section.append(heading, form); return section; };
const inputGroup = (label: string, id: string, kind: "input" | "textarea"): HTMLInputElement | HTMLTextAreaElement => { const node = document.createElement(kind); node.id = id; node.dataset.label = label; return node; };
const labelFor = (field: HTMLInputElement | HTMLTextAreaElement): HTMLLabelElement => { const label = document.createElement("label"); label.htmlFor = field.id; label.textContent = field.dataset.label ?? ""; return label; };
const button = (label: string, action: () => void, className = ""): HTMLButtonElement => { const node = document.createElement("button"); node.type = "button"; node.className = className; node.textContent = label; node.addEventListener("click", action); return node; };
const text = (value: string): HTMLElement => { const node = document.createElement("p"); node.textContent = value; return node; };
const formatBytes = (size: number): string => size < 1024 ? `${size} bytes` : size < 1024 * 1024 ? `${(size / 1024).toFixed(1)} KiB` : `${(size / 1024 / 1024).toFixed(1)} MiB`;
