import type { AppState } from "../../app/Store";
import { categoryLabels, itemCategories, resolveItemVisual, type ItemCategory } from "../../domain/items/items";
import { ItemIcon } from "../icons/itemIcons";

export type ItemScreenActions = { showItemList: () => void; showItemDetail: (id: string) => void; showItemCreate: () => void; createItem: (input: { name: string; category: ItemCategory; description: string }) => Promise<string | null> };
export const ItemsScreen = (state: AppState, actions: ItemScreenActions): HTMLElement => state.itemView === "create" ? createScreen(state, actions) : state.itemView === "detail" ? detailScreen(state, actions) : listScreen(state, actions);
const base = (title: string): [HTMLElement, HTMLElement] => { const section = document.createElement("section"); section.className = "content-card items-screen"; const heading = document.createElement("h2"); heading.id = "items-heading"; heading.tabIndex = -1; heading.textContent = title; section.setAttribute("aria-labelledby", heading.id); return [section, heading]; };
const live = (message: string): HTMLElement => { const node = document.createElement("p"); node.className = "item-live"; node.setAttribute("role", "status"); node.setAttribute("aria-live", "polite"); node.textContent = message; return node; };
const listScreen = (state: AppState, actions: ItemScreenActions): HTMLElement => { const [section, heading] = base("アイテム"); const count = document.createElement("p"); count.className = "eyebrow"; count.textContent = `${state.items.length}件登録`; const create = button("アイテムを登録", actions.showItemCreate, "primary-button item-create-button"); const list = document.createElement("div"); list.className = "item-list"; const ordered = [...state.items].sort((a, b) => (a.source === "preset" ? 0 : 1) - (b.source === "preset" ? 0 : 1) || a.name.localeCompare(b.name, "ja") || a.itemId.localeCompare(b.itemId)); ordered.forEach((item) => { const row = button("", () => actions.showItemDetail(item.itemId), "item-row"); row.dataset.itemId = item.itemId; row.append(ItemIcon(item.visual.iconKey)); const copy = document.createElement("span"); const name = document.createElement("strong"); name.textContent = item.name; const category = document.createElement("small"); category.textContent = categoryLabels[item.category]; copy.append(name, category); row.append(copy); list.append(row); }); section.append(heading, count, create, list, live(state.itemMessage)); return section; };
const detailScreen = (state: AppState, actions: ItemScreenActions): HTMLElement => { const item = state.items.find(({ itemId }) => itemId === state.selectedItemId); if (!item) return listScreen(state, actions); const [section, heading] = base(item.name); const back = button("一覧へ戻る", actions.showItemList); const visual = resolveItemVisual(item); const hero = document.createElement("div"); hero.className = "item-hero"; hero.append(ItemIcon(visual.kind === "icon" ? visual.iconKey : "category", item.name)); const category = document.createElement("p"); category.textContent = `カテゴリ：${categoryLabels[item.category]}`; const description = document.createElement("p"); description.className = "item-description"; description.textContent = item.description || "説明はありません。"; const source = document.createElement("p"); source.className = "eyebrow"; source.textContent = item.source === "preset" ? "プリセット" : item.source === "user" ? "ユーザー登録" : "イベント"; section.append(back, hero, heading, category, description, source, text("画像は任意です。現在は汎用アイコンで表示しています。"), live(state.itemMessage)); return section; };
const createScreen = (state: AppState, actions: ItemScreenActions): HTMLElement => { const [section, heading] = base("アイテムを登録"); const form = document.createElement("form"); form.className = "item-form"; const name = inputGroup("アイテム名", "item-name", "input") as HTMLInputElement; name.maxLength = 40; name.required = true; const category = document.createElement("select"); category.id = "item-category"; itemCategories.forEach((id) => { const option = document.createElement("option"); option.value = id; option.textContent = categoryLabels[id]; category.append(option); }); const categoryLabel = document.createElement("label"); categoryLabel.htmlFor = category.id; categoryLabel.textContent = "カテゴリ"; const description = inputGroup("説明（任意）", "item-description", "textarea") as HTMLTextAreaElement; description.maxLength = 280; const message = live(state.itemMessage); const submit = button("登録する", () => undefined, "primary-button"); submit.type = "submit"; form.append(labelFor(name), name, categoryLabel, category, labelFor(description), description, message, submit, button("キャンセル", actions.showItemList)); form.addEventListener("submit", async (event) => { event.preventDefault(); submit.disabled = true; const error = await actions.createItem({ name: name.value, category: category.value as ItemCategory, description: description.value }); if (error) { message.textContent = error; submit.disabled = false; } }); section.append(heading, form); return section; };
const inputGroup = (label: string, id: string, kind: "input" | "textarea"): HTMLInputElement | HTMLTextAreaElement => { const node = document.createElement(kind); node.id = id; node.dataset.label = label; return node; };
const labelFor = (field: HTMLInputElement | HTMLTextAreaElement): HTMLLabelElement => { const label = document.createElement("label"); label.htmlFor = field.id; label.textContent = field.dataset.label ?? ""; return label; };
const button = (label: string, action: () => void, className = ""): HTMLButtonElement => { const node = document.createElement("button"); node.type = "button"; node.className = className; node.textContent = label; node.addEventListener("click", action); return node; };
const text = (value: string): HTMLElement => { const node = document.createElement("p"); node.textContent = value; return node; };
