import type { AppState } from "../../app/Store";
import type { CharacterId } from "../../domain/characters/characterTypes";
import { MAP_BACKGROUND_IDS, type MapBackgroundId } from "../../domain/assets/mapBackgrounds";

export type CharacterImageUi = { phase: "marker" | "loading" | "image" | "preview" | "saving" | "delete_confirm" | "deleting" | "error"; url: string | null; fileName?: string; mimeType?: string; byteSize?: number; message?: string };
export type MapBackgroundUi = { phase: "fallback" | "loading" | "image" | "preview" | "saving" | "delete_confirm" | "deleting" | "error"; url: string | null; fileName?: string; mimeType?: string; byteSize?: number; message?: string };
export type SettingsActions = { chooseMapBackground: (id: MapBackgroundId, file: File) => void; saveMapBackground: (id: MapBackgroundId) => void; cancelMapBackground: (id: MapBackgroundId) => void; confirmDeleteMapBackground: (id: MapBackgroundId) => void; deleteMapBackground: (id: MapBackgroundId) => void; chooseCharacterImage: (id: CharacterId, file: File) => void; saveCharacterImage: (id: CharacterId) => void; cancelCharacterImage: (id: CharacterId) => void; confirmDeleteCharacterImage: (id: CharacterId) => void; deleteCharacterImage: (id: CharacterId) => void };
export const SettingsScreen = (state: AppState, actions: SettingsActions, images: Record<CharacterId, CharacterImageUi>, backgrounds: Record<MapBackgroundId, MapBackgroundUi>): HTMLElement => {
  const section = document.createElement("section"); section.className = "content-card settings-screen"; section.append(text("h2", "ふたりの見た目"), text("p", "端末内の画像を人物ピンと代理表示に使えます。画像は外部へ送信しません。"));
  state.characters.forEach((character) => { const ui = images[character.characterId], card = document.createElement("section"); card.className = "character-image-card"; card.append(text("h3", character.characterId === "user" ? "主人公" : character.name)); const preview = document.createElement("div"); preview.className = "character-image-preview"; if (ui.url) { const img = document.createElement("img"); img.src = ui.url; img.alt = ""; preview.append(img); } else preview.append(text("strong", character.marker)); card.append(preview);
    const controls = document.createElement("div"); controls.className = "character-image-controls"; const input = document.createElement("input"); input.type = "file"; input.accept = "image/png,image/jpeg,image/webp"; input.id = `character-image-${character.characterId}`; input.disabled = ["saving", "deleting"].includes(ui.phase); input.addEventListener("change", () => { const file = input.files?.[0]; if (file) actions.chooseCharacterImage(character.characterId, file); }); const label = text("label", character.imageAssetId ? "画像を変更" : "画像を追加", "button-label"); label.htmlFor = input.id; controls.append(input, label);
    if (ui.phase === "preview" || ui.phase === "saving") { controls.append(text("p", `${ui.fileName ?? ""}\n${ui.mimeType ?? ""}・${formatBytes(ui.byteSize ?? 0)}`), button("この画像を保存", () => actions.saveCharacterImage(character.characterId), ui.phase === "saving"), button("選び直す", () => input.click(), ui.phase === "saving"), button("キャンセル", () => actions.cancelCharacterImage(character.characterId), ui.phase === "saving")); }
    if (character.imageAssetId && ui.phase !== "preview" && ui.phase !== "saving") controls.append(button(ui.phase === "delete_confirm" ? "削除する" : "画像を削除", () => ui.phase === "delete_confirm" ? actions.deleteCharacterImage(character.characterId) : actions.confirmDeleteCharacterImage(character.characterId), ui.phase === "deleting"));
    const live = text("p", ui.phase === "delete_confirm" ? "画像だけを削除します。よろしいですか？" : ui.message ?? "", "character-image-live"); live.setAttribute("role", "status"); live.setAttribute("aria-live", "polite"); controls.append(live); card.append(controls); section.append(card); });
  section.append(text("h2", "マップ背景"), text("p", "室内と庭へ別々の画像を登録できます。画像がない時は仮背景を使います。"));
  MAP_BACKGROUND_IDS.forEach((mapId) => { const ui = backgrounds[mapId], visual = state.mapVisuals[mapId], card = document.createElement("section"); card.className = "map-background-card"; card.append(text("h3", mapId === "starter_house_interior" ? "室内" : "庭")); const preview = document.createElement("div"); preview.className = `map-background-preview map-canvas--${mapId === "starter_house_interior" ? "interior" : "outdoor"}`; if (ui.url) { const img = document.createElement("img"); img.src = ui.url; img.alt = ""; img.addEventListener("error", () => { img.remove(); preview.append(text("span", "仮背景を使用中")); }); preview.append(img); } else preview.append(text("span", "仮背景を使用中")); card.append(preview);
    const controls = document.createElement("div"); controls.className = "character-image-controls"; const input = document.createElement("input"); input.type = "file"; input.accept = "image/png,image/jpeg,image/webp"; input.id = `map-background-${mapId}`; input.disabled = ["saving", "deleting"].includes(ui.phase); input.addEventListener("change", () => { const file = input.files?.[0]; if (file) actions.chooseMapBackground(mapId, file); }); const label = text("label", visual.backgroundAssetId ? "画像を変更" : "画像を追加", "button-label"); label.htmlFor = input.id; controls.append(input, label);
    if (["preview", "saving"].includes(ui.phase)) controls.append(text("p", `${ui.fileName ?? ""}
${ui.mimeType ?? ""}・${formatBytes(ui.byteSize ?? 0)}`), button("この背景を保存", () => actions.saveMapBackground(mapId), ui.phase === "saving"), button("選び直す", () => input.click(), ui.phase === "saving"), button("キャンセル", () => actions.cancelMapBackground(mapId), ui.phase === "saving"));
    if (visual.backgroundAssetId && !["preview", "saving"].includes(ui.phase)) controls.append(button(ui.phase === "delete_confirm" ? "背景画像だけを削除する" : "画像を削除", () => ui.phase === "delete_confirm" ? actions.deleteMapBackground(mapId) : actions.confirmDeleteMapBackground(mapId), ui.phase === "deleting"));
    const message = ui.phase === "delete_confirm" ? "背景画像だけを削除します。マップ、地点、人物、アイテム、イベント、セーブデータは残り、仮背景へ戻ります。" : ui.message ?? ""; const live = text("p", message, "character-image-live"); live.setAttribute("role", "status"); live.setAttribute("aria-live", "polite"); controls.append(live); card.append(controls); section.append(card); }); return section;
};
const text = <K extends keyof HTMLElementTagNameMap>(tag: K, value: string, className = ""): HTMLElementTagNameMap[K] => { const element = document.createElement(tag); element.textContent = value; element.className = className; return element; };
const button = (label: string, action: () => void, disabled = false): HTMLButtonElement => { const element = document.createElement("button"); element.type = "button"; element.textContent = label; element.disabled = disabled; element.addEventListener("click", action); return element; };
const formatBytes = (bytes: number): string => bytes < 1024 ? `${bytes} B` : bytes < 1024 * 1024 ? `${(bytes / 1024).toFixed(1)} KiB` : `${(bytes / 1024 / 1024).toFixed(1)} MiB`;
