import type { AppState } from "../../app/Store";
import type { CharacterId } from "../../domain/characters/characterTypes";
import { MAP_BACKGROUND_IDS, type MapBackgroundId } from "../../domain/assets/mapBackgrounds";
import { characterPinStyle, type CharacterPinVisual } from "../../domain/characters/characterPinVisual";

export type CharacterImageUi = { phase: "marker" | "loading" | "image" | "preview" | "saving" | "delete_confirm" | "deleting" | "error"; url: string | null; fileName?: string; mimeType?: string; byteSize?: number; message?: string };
export type MapBackgroundUi = { phase: "fallback" | "loading" | "image" | "preview" | "saving" | "delete_confirm" | "deleting" | "error"; url: string | null; fileName?: string; mimeType?: string; byteSize?: number; message?: string };
export type CharacterVisualUi = { editing: boolean; saving: boolean; draft: CharacterPinVisual; message: string };
export type SettingsActions = { openCharacterVisual: (id: CharacterId) => void; updateCharacterVisual: (id: CharacterId, value: CharacterPinVisual) => void; resetCharacterVisual: (id: CharacterId) => void; saveCharacterVisual: (id: CharacterId) => void; cancelCharacterVisual: (id: CharacterId) => void; openMapBackgroundPicker: (id: MapBackgroundId) => void; saveMapBackground: (id: MapBackgroundId) => void; cancelMapBackground: (id: MapBackgroundId) => void; confirmDeleteMapBackground: (id: MapBackgroundId) => void; deleteMapBackground: (id: MapBackgroundId) => void; openCharacterImagePicker: (id: CharacterId) => void; saveCharacterImage: (id: CharacterId) => void; cancelCharacterImage: (id: CharacterId) => void; confirmDeleteCharacterImage: (id: CharacterId) => void; deleteCharacterImage: (id: CharacterId) => void };
export const SettingsScreen = (state: AppState, actions: SettingsActions, images: Record<CharacterId, CharacterImageUi>, backgrounds: Record<MapBackgroundId, MapBackgroundUi>, visuals: Record<CharacterId, CharacterVisualUi>): HTMLElement => {
  const section = document.createElement("section"); section.className = "content-card settings-screen"; section.append(text("h2", "ふたりの見た目"), text("p", "端末内の画像を人物ピンと代理表示に使えます。画像は外部へ送信しません。"));
  state.characters.forEach((character) => { const ui = images[character.characterId], card = document.createElement("section"); card.className = "character-image-card"; card.append(text("h3", character.characterId === "user" ? "主人公" : character.name)); const preview = document.createElement("div"); preview.className = "character-image-preview"; if (ui.url) { const img = document.createElement("img"); img.src = ui.url; img.alt = ""; preview.append(img); } else preview.append(text("strong", character.marker)); card.append(preview);
    const controls = document.createElement("div"); controls.className = "character-image-controls"; const busy = ["saving", "deleting"].includes(ui.phase);
    if (ui.phase === "preview" || ui.phase === "saving") { controls.append(text("p", `${ui.fileName ?? ""}\n${ui.mimeType ?? ""}・${formatBytes(ui.byteSize ?? 0)}`), button("この画像を保存", () => actions.saveCharacterImage(character.characterId), ui.phase === "saving"), button("選び直す", () => actions.openCharacterImagePicker(character.characterId), ui.phase === "saving"), button("キャンセル", () => actions.cancelCharacterImage(character.characterId), ui.phase === "saving")); } else controls.append(button(character.imageAssetId ? "画像を変更" : "画像を追加", () => actions.openCharacterImagePicker(character.characterId), busy));
    if (character.imageAssetId && ui.phase !== "preview" && ui.phase !== "saving") controls.append(button(ui.phase === "delete_confirm" ? "削除する" : "画像を削除", () => ui.phase === "delete_confirm" ? actions.deleteCharacterImage(character.characterId) : actions.confirmDeleteCharacterImage(character.characterId), ui.phase === "deleting"));
    if (character.imageAssetId && ui.phase === "image") controls.append(button("表示を調整", () => actions.openCharacterVisual(character.characterId)));
    const visualUi = visuals[character.characterId];
    if (visualUi.editing) card.append(visualEditor(character.characterId, ui.url!, visualUi, actions));
    const live = text("p", visualUi.message || (ui.phase === "delete_confirm" ? "画像だけを削除します。よろしいですか？" : ui.message ?? ""), "character-image-live"); live.setAttribute("role", "status"); live.setAttribute("aria-live", "polite"); controls.append(live); card.append(controls); section.append(card); });
  section.append(text("h2", "マップ背景"), text("p", "室内と庭へ別々の画像を登録できます。画像がない時は仮背景を使います。"));
  MAP_BACKGROUND_IDS.forEach((mapId) => { const ui = backgrounds[mapId], visual = state.mapVisuals[mapId], card = document.createElement("section"); card.className = "map-background-card"; card.append(text("h3", mapId === "starter_house_interior" ? "室内" : "庭")); const preview = document.createElement("div"); preview.className = `map-background-preview map-canvas--${mapId === "starter_house_interior" ? "interior" : "outdoor"}`; if (ui.url) { const img = document.createElement("img"); img.src = ui.url; img.alt = ""; img.addEventListener("error", () => { img.remove(); preview.append(text("span", "仮背景を使用中")); }); preview.append(img); } else preview.append(text("span", "仮背景を使用中")); card.append(preview);
    const controls = document.createElement("div"); controls.className = "character-image-controls"; const busy = ["saving", "deleting"].includes(ui.phase);
    if (["preview", "saving"].includes(ui.phase)) controls.append(text("p", `${ui.fileName ?? ""}\n${ui.mimeType ?? ""}・${formatBytes(ui.byteSize ?? 0)}`), button("この背景を保存", () => actions.saveMapBackground(mapId), ui.phase === "saving"), button("選び直す", () => actions.openMapBackgroundPicker(mapId), ui.phase === "saving"), button("キャンセル", () => actions.cancelMapBackground(mapId), ui.phase === "saving")); else controls.append(button(visual.backgroundAssetId ? "画像を変更" : "画像を追加", () => actions.openMapBackgroundPicker(mapId), busy));
    if (visual.backgroundAssetId && !["preview", "saving"].includes(ui.phase)) controls.append(button(ui.phase === "delete_confirm" ? "背景画像だけを削除する" : "画像を削除", () => ui.phase === "delete_confirm" ? actions.deleteMapBackground(mapId) : actions.confirmDeleteMapBackground(mapId), ui.phase === "deleting"));
    const message = ui.phase === "delete_confirm" ? "背景画像だけを削除します。マップ、地点、人物、アイテム、イベント、セーブデータは残り、仮背景へ戻ります。" : ui.message ?? ""; const live = text("p", message, "character-image-live"); live.setAttribute("role", "status"); live.setAttribute("aria-live", "polite"); controls.append(live); card.append(controls); section.append(card); }); return section;
};
const visualEditor = (id: CharacterId, url: string, ui: CharacterVisualUi, actions: SettingsActions): HTMLElement => {
  const editor = document.createElement("section"); editor.className = "pin-visual-editor"; editor.append(text("h4", "人物ピンの表示調整"), text("p", "接地点は地点ガイドへ合わせる画像上の足元です。表示位置は切抜き枠内で見せる部分です。"));
  const preview = document.createElement("div"); preview.className = "pin-visual-preview map-canvas--interior"; const guide = text("span", "地点", "pin-location-guide"); const pin = document.createElement("span"); pin.className = "pin-visual-preview-image"; const image = document.createElement("img"); image.src = url; image.alt = "調整中の人物ピン"; pin.append(image); preview.append(guide, pin); editor.append(preview);
  const apply = (draft: CharacterPinVisual) => { const style = characterPinStyle(draft); pin.style.width = style.width; pin.style.height = style.height; pin.style.transform = style.transform; image.style.objectPosition = style.objectPosition; actions.updateCharacterVisual(id, draft); };
  apply(ui.draft);
  const fields: Array<[keyof CharacterPinVisual, string, number, number, number]> = [["anchorX", "接地点・左右", 0, 100, 1], ["anchorY", "接地点・上下", 0, 100, 1], ["scale", "表示倍率", .5, 2, .05], ["objectPositionX", "表示位置・左右", 0, 100, 1], ["objectPositionY", "表示位置・上下", 0, 100, 1]];
  fields.forEach(([key, labelText, min, max, step]) => { const label = document.createElement("label"), output = document.createElement("output"), input = document.createElement("input"); input.type = "range"; input.min = String(min); input.max = String(max); input.step = String(step); input.value = String(ui.draft[key]); output.textContent = String(ui.draft[key]); label.append(text("span", labelText), output, input); input.addEventListener("input", () => { const draft = { ...ui.draft, [key]: Number(input.value) }; output.textContent = input.value; apply(draft); ui.draft = draft; }); editor.append(label); });
  const controls = document.createElement("div"); controls.className = "pin-visual-actions"; controls.append(button("初期値に戻す", () => actions.resetCharacterVisual(id), ui.saving), button("この表示設定を保存", () => actions.saveCharacterVisual(id), ui.saving), button("キャンセル", () => actions.cancelCharacterVisual(id), ui.saving)); editor.append(controls); return editor;
};
const text = <K extends keyof HTMLElementTagNameMap>(tag: K, value: string, className = ""): HTMLElementTagNameMap[K] => { const element = document.createElement(tag); element.textContent = value; element.className = className; return element; };
const button = (label: string, action: () => void, disabled = false): HTMLButtonElement => { const element = document.createElement("button"); element.type = "button"; element.textContent = label; element.disabled = disabled; element.addEventListener("click", action); return element; };
const formatBytes = (bytes: number): string => bytes < 1024 ? `${bytes} B` : bytes < 1024 * 1024 ? `${(bytes / 1024).toFixed(1)} KiB` : `${(bytes / 1024 / 1024).toFixed(1)} MiB`;
